import Vue from 'vue'
import { Button, NavBar, Form, Field, Tabbar, TabbarItem, Icon, CountDown, Toast, Image as VanImage, Grid, GridItem, Cell, CellGroup, Dialog } from 'vant'
Vue.use(Button)
Vue.use(NavBar)
Vue.use(Form)
Vue.use(Field)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Icon)
Vue.use(CountDown)
Vue.use(Toast)
Vue.use(VanImage)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Dialog)
